### ISSUE TITLE
Can't install latest version of holoiso_tweaked

### ISSUE THREAD

**Issue by iero15** [zweiler2/HoloISO_Nvidia#14]
## Issue : cant install latest version of holoiso_tweaked
 when I try to install the latest holoiso_tweaked with this link https://repo.ewan1011.me/f/68494cd0e59b4b3aa9a0/?dl=1 it won't download

**Comment by Ew4n1011** [comment]
Hi, server admin here.

Seems something went wrong with the SSL resolving on the server. I've restarted it and it seems to be running now, sorry for the downtime.
