### ISSUE TITLE
Can't access download links.

### ISSUE THREAD

**Issue by Paulicat** [zweiler2/HoloISO_Nvidia#15]
Was previously able to download the iso's but since a few days ago I'm getting the attached error.
Also tried with Chrome, error screenshot attached.
Tried 2 different ISPs, fairly confident it's not on my end but I'm not certain.
<img width="586" alt="Screenshot 2023-10-28 at 5 14 07 PM" src="https://github.com/zweiler2/HoloISO_Tweaked/assets/4650650/785bb182-a8f9-4ebf-a607-b8cb3454d3cc">
<img width="652" alt="Screenshot 2023-10-28 at 5 16 22 PM" src="https://github.com/zweiler2/HoloISO_Tweaked/assets/4650650/1315329b-44ec-44aa-9630-7eec041d056b">

**Comment by Ew4n1011** [comment]
Hey, server admin here.

Seems that seafile (the hosting service) didn't like the server update, and caused it to crash. Just rebooted and tested it now, should be working.

**Comment by Paulicat** [comment]
Working great now thank you for the quick action!!!
