### ISSUE TITLE
wifiが使えない

### ISSUE THREAD

**Issue by kzkzkzkzkzk** [zweiler2/HoloISO_Nvidia#16]
I can't get wifi on my rogally.
This is the latest ISO.

**Comment by Paulicat** [comment]
Also lost wifi on OneXPlayer2 which had working wifi on last iso build.

**Comment by zweiler2** [comment]
Closing this issue as i assume it is fixed due to [this](https://github.com/zweiler2/HoloISO_Tweaked/issues/12#issuecomment-1807530713) and [this](https://github.com/zweiler2/HoloISO_Tweaked/issues/12#issuecomment-1808660610) comment.
If it isn't, in the newest ISO, then feel free to reopen.
