### ISSUE TITLE
Bluetooth problem

### ISSUE THREAD

**Issue by iero15** [zweiler2/HoloISO_Nvidia#17]
## Your Issue: Bluetooth error
```
dependency failed to start bluetooth service
```

## Your device's full specs
```
CPU: *AMD Ryzen 5600 6-core*
GPU: *Nvidia Geforce RTX 3050 OC edition*
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20230918.0956
```

## Have you updated your installation recently?
```
I yesterday did a clean install
```

**Comment by zweiler2** [comment]
Please test [this](https://repo.ewan1011.me/f/a7883a1364814ead963d/?dl=1) ISO @iero15  and see if it is fixed for you.
And if not, then which bluetooth chip do you have? (`lspci` and/or `lsusb` in the terminal may help you find out)
Bluetooth is confirmed working, with this ISO, for the OneXPlayer 2.
SHA512: `caec85f157ed7f66e78098b9209b6cbc6fff4f5b11589f4bdf6b960e4d73ea8c46bb371afd6510b01b4e800b1dd57c8b983538df772a2ee6e9539a7cc3086f4e`

**Comment by iero15** [comment]
Thanks it works!

**Comment by iero15** [comment]
Bluetooth sometimes works and sometimes doesn't
