### ISSUE TITLE
[Report] With Ventoy 1.0.91 not work

### ISSUE THREAD

**Issue by Labsdj** [zweiler2/HoloISO_Nvidia#2]
## Your Issue:
```
Is boot with ventoy 1.0.91 but when i try install not get succeful
i think any bug about with ventoy use and connection to internet not apear
```

## Your device's full specs
```
CPU: AMD R5 1600AF
GPU: AMD RX570 4GB Sapphire Nitro +
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
nawww
```

**Comment by zweiler2** [comment]
Have you tried again recently with updated Ventoy and a newer ISO?

**Comment by zweiler2** [comment]
Closing due to no response. Feel free to reopen if the issue persists
