### ISSUE TITLE
issue in chroot_holoiso.sh that delete all data.

### ISSUE THREAD

**Issue by grimlokason** [zweiler2/HoloISO_Nvidia#23]
## Your Issue:
All the data on my disk has been deleted while using the chroot script on the desktop of the installation iso.
If we take a look at https://github.com/zweiler2/HoloISO_Tweaked/blob/Tweaked_5.x/airootfs/etc/holoinstall/post_install/chroot_holoiso.sh ,
We can see that there is a ```sudo rm -rf ${MOUNT_DIR}``` , even if there is a check before, it seems that it failed in my case after launching the script twice.
I'm afraid that i'm won't be able to reproduce the issue.

## Your device's full specs
not related

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
has been deleted :'(

## Have you updated your installation recently?
Just after a reinstallation with a fresh usb key with the last iso without deleteing my home dir

**Comment by zweiler2** [comment]
I'm so sorry. Something like this should never happen. I'll fix this asap.

**Comment by grimlokason** [comment]
Hi !

Just spotted the issue.
it's the "umount -l" : 
```-l, --lazy
           Lazy unmount. Detach the filesystem from the file hierarchy
           now, and clean up all references to this filesystem as soon
           as it is not busy anymore.

           A system reboot would be expected in near future if you’re
           going to use this option for network filesystem or local
           filesystem with submounts. The recommended use-case for
           umount -l is to prevent hangs on shutdown due to an
           unreachable network share where a normal umount will hang due
           to a downed server or a network partition. Remounts of the
           share will not be possible.```

NB : I'll test extundelete this evening ^^'

**Comment by zweiler2** [comment]
Fixed by this [commit](https://github.com/zweiler2/HoloISO_Tweaked/commit/72ad9ffcce8b93fb3a97294d60135abdf5f6393b), but one "i" too much and GH didn't close this automatically oops ;)
