### ISSUE TITLE
Screen Flashing Rapidly 

### ISSUE THREAD

**Issue by treypop** [zweiler2/HoloISO_Nvidia#28]
## Your Issue:
```
The screen is flashing rapidly and not showing any display updates after install. It prevents me from finishing the install.
```

## Your device's full specs
```
Lenovo LOQ 15IRH8
CPU: Intel i5-13420H
GPU: GeForce RTX 3050
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
I installed using Tweaked v5.0.2.2
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
N/a
```

## Have you updated your installation recently?
```
No
```

**Comment by zweiler2** [comment]
Does this issue persist in the newest ISO?

**Comment by treypop** [comment]
Yes, the black screen fix script did the trick
