### ISSUE TITLE
Switch away from GDrive as an ISO host

### ISSUE THREAD

**Issue by ShalokShalom** [zweiler2/HoloISO_Nvidia#3]
Hi there 👋🏻 

I see you are the new maintainer of HoloISO ;) 

I have seen, that Google repos are still used for this project.

As you may know, they are insecure since they use no form of encryption or checksums.

See this: https://radixproject.org/

**Comment by pastaq** [comment]
Alternatively, the AUR can be used for packages, so long as they can be installed on any arch deployment.

**Comment by zweiler2** [comment]
@ShalokShalom I do provide the SHA512 of the ISOs, so you can be sure that it hasn't been tampered with or something.  
@pastaq How would i package an ~3.1GB ISO for the AUR? As far as i know only PKGBUILDs are allowed there...  
To be clear: I am open to ideas to move away from GDrive, but as of now it seems to be the best option for me...

**Comment by ShalokShalom** [comment]
Aaaand .. Radix? Or another host?

**Comment by ShalokShalom** [comment]
Oracle has an amazing Free Tier. https://www.oracle.com/cloud/free/

**Comment by zweiler2** [comment]
Never heard of Radix before. It looks like i would have to apply to a waitlist, then probably talk a bit back and forth with them to get taken as a partner and for a small fork of a niche project this seems like a bit of a (unneeded) hassle at the moment.  
Oracle looks nice, though a bit overkill to use it just as a fileserver and their wording on whats actually included in the free tier is confusing.

**Comment by ShalokShalom** [comment]
So we will just stay on insecure server? 

I ask this, since I would otherwise recommend the repo. 

People are still linking to the original one, and I can only recommend Chimera at this point, which is using Gnome. 

And I dont like to recommend an inherently insecure OS.

**Comment by Ew4n1011** [comment]
I also have a self hosted repo so it could be hosted on there. It is hosted on oracle cloud in France, has TLS and is currently only used for a small aur repo so I could definitely make some room for it.

**Comment by zweiler2** [comment]
Closing this issue because @Ew4n1011 kindly provided his server.

**Comment by ShalokShalom** [comment]
Wonderful 😄

**Comment by NewYearNewPhil** [comment]
I'm getting an SSL error when trying to download any of the non Google Cloud Releases:
```
curl https://repo.ewan1011.me/f/b2f8b2ea09584f3da9f7/?dl=1
> curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.
```

**Comment by Ew4n1011** [comment]
Hey, repo server admin here

Seems rebooting the server for security updates crashed seafile (the service running the web server), it should be back up and running now

**Comment by NewYearNewPhil** [comment]
Hi @Ew4n1011, thanks for the super swift response!
I'll abort the current installation process and use the most recent release then ;)

I understand that using Google Drive isnt optimal, but maybe it should be considered to still provide Google downloads as a fallback option - downloading from there is also significantly faster

**Comment by ShalokShalom** [comment]
Torrents could also help. 

Or something like wormhole.app
