### ISSUE TITLE
Mouse not work

### ISSUE THREAD

**Issue by Labsdj** [zweiler2/HoloISO_Nvidia#36]
Mouse not work on last iso update i try many mouse usb connection and a one ps2 connection mouse. And nothing work im stuck on system and need to force shuthdown the pc cannot avance to next pass. To install this system.

**Comment by GuestSneezeOSDev** [comment]
This project is no longer in development but i will help, Have you tried either using a USB 2 or USB 3 or have tried using any adapters?

**Comment by GuestSneezeOSDev** [comment]
Hit `ctrl + alt +f2` to enter console interface and type ```modinfo usbmouse``` tell me the output

**Comment by GuestSneezeOSDev** [comment]
Duplicate of https://github.com/zweiler2/HoloISO_Tweaked/issues/5

**Comment by Labsdj** [comment]
Yes without any sucess
and the GuestSneezeOS not install on my disk i try on my specs pc R5 1600AF with RX 6600 8GB and 16GB DDR4 With 1 M.2 256GB + 1 SSD 480GB + 1 SSD 120GB + 1 HD 1TB + 1 USB 3.0 Hd 1TB

**Comment by GuestSneezeOSDev** [comment]
did you try the alternative installers?

**Comment by GuestSneezeOSDev** [comment]
@Labsdj would you like to beta test newer versions of GuestSneezeOS?

**Comment by Labsdj** [comment]
Yes

**Comment by GuestSneezeOSDev** [comment]
join the orginizaton

**Comment by zweiler2** [comment]
> This project is no longer in development but i will help, Have you tried either using a USB 2 or USB 3 or have tried using any adapters?

@GuestSneezeOSDev This is not true. This is a free time project.
Yes i have neglected the issues for a bit, but i still do updates to this project.

**Comment by zweiler2** [comment]
Closing due to duplicate of #5.
