### ISSUE TITLE
issues on boot

### ISSUE THREAD

**Issue by Watermelon1263** [zweiler2/HoloISO_Nvidia#37]
## Your Issue:
issues on startup
*type your problem here*
FAILED Failed to start Steam Patch Loader  FAILED! Failed to start service to restart steam-patch on system boot  

## Your device's full specs
Intel i7 13700k
msi 4070ti
32gb ram

## Your OS version 
https://github.com/zweiler2/HoloISO_Tweaked/releases/tag/Tweaked_v5.1.1

## Have you updated your installation recently?
```
*yes or no*
```
![20240711_180510](https://github.com/user-attachments/assets/7e2a3794-7482-4e60-ae1c-f58dfb5f9953)

**Comment by Watermelon1263** [comment]
I reinstalled it but now it says disabling IQR #17

**Comment by Watermelon1263** [comment]
![20240711_185354](https://github.com/user-attachments/assets/607ad778-5ebc-4d58-9564-ff173949e38a)

**Comment by zweiler2** [comment]
Why are you using the steam patch? It is only for the ASUS ROG Ally, OneXPlayer 2 and Legion Go devices...
Have you tried installing without it?

**Comment by Watermelon1263** [comment]
I just installed the iso, I didn't see any option to install without it
