### ISSUE TITLE
Install/Updated failed mesa and other packages 404 error

### ISSUE THREAD

**Issue by vinicius-trev** [zweiler2/HoloISO_Nvidia#40]
## Your Issue:
While doing a fresh install in an Intel Compute Stick PC I noticed that I got no video output at all during first boot. After some investigation, I noticed that some packages were not being installed due to 404 error in the repo.ewan1011.eu/holoiso-tweaked-main repo.  For example, the package holoiso-tweaked-mesa-1:24.1.4.2-x86_64.pkg.tar.zst couldn't be found, but searching in the mirror I can find it [holoiso-tweaked-mesa-1_24.0.5-1-x86_64.pkg.tar.zst](https://repo.ewan1011.eu/holoiso-tweaked-main/holoiso-tweaked-mesa-1_24.0.5-1-x86_64.pkg.tar.zst)

I don't know if that is due the difference in the package name or another problem, but doing a curl or wget in that URL I can download correctly the package, but the pacman -Suy still fails

## Your device's full specs
```
CPU: Core m5-6Y57
GPU: Intel HD Graphics 515
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20231120.1038
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
*Please put anything here if you tried to launch session separately*
```

## Have you updated your installation recently?
```
no, fresh install
```

**Comment by Ew4n1011** [comment]
Hey, guy that hosts the repo here

@zweiler2 notified me of this yesterday, it seems that moving the files to windows to setup with samba has caused all files that had a : to change to a _

I am aware of this and to fix it it'll take a bit since I have to go file by file, checking which have changed and which haven't

Sorry for the bugs, this is why I hate windows 🤦🏼‍♂️, I'll try and get it fixed as soon as possible

**Comment by vinicius-trev** [comment]
oka, no worries, if help is needed lmk!

**Comment by vinicius-trev** [comment]
@Ew4n1011 I was doing a quick test here and noticed that most of the files that may need fixes follow that pattern:

- `*-1_*` -> `*-1:*`
- `*-2_*` -> `*-2:*`

I don't know the correct file names for them, that's just a guess to facilitate things and try to get them fixed faster. I did this shell script that will rename those occurrences ignoring the x86_64 pattern.

```bash
#!/bin/bash
for i in *; do
        if [[ "$i" == *"1_"* ]]; then
                mv "$i" "`echo $i | sed "s/1_/1:/"`";
        elif [[ "$i" == *"2_"* ]] ; then
                mv "$i" "`echo $i | sed "s/2_/2:/"`";
        fi
done
```

To test it, you can replace the `mv` with `echo` to check if they were renamed right or `cp` them to another directory

**Comment by Ew4n1011** [comment]
@vinicius-trev Thanks for the script! That helps a lot!

I have a look later tonight to see if it works.

**Comment by Ew4n1011** [comment]
Sorry for taking a while, this week has been busy 😅

@vinicius-trev  Could you test if all is working ok now? I replaced it with a script so they all should be with the correct naming scheme, but I have no way to test it since I can't check the original file names.

**Comment by vinicius-trev** [comment]
Hey @Ew4n1011, I can test tomorrow/monday evening

**Comment by vinicius-trev** [comment]
@Ew4n1011, sorry for the delay, I was traveling and didn't have access to my htpc.

Now everything seems to work for the packages, thank you so much. It is still not producing any video output in my compute stick, but that's another issue.

**Comment by Ew4n1011** [comment]
It's fine, I'd actually forgotten about this too so no worries. Thanks!
