### ISSUE TITLE
Update Instructions

### ISSUE THREAD

**Issue by borger** [zweiler2/HoloISO_Nvidia#7]
## Your Issue:
```
I would like to have the instructions on the recommended steps to perform an update. e.g. I've installed from version 4.1.3 and I want to update it to 4.1.4 HotFix. What's the update steps without losing my home/configs? Should I use the newest ISO? Run a command on the installed OS?
```

## Your device's full specs
```
CPU: AMD Ryzen 9 7950X3D 
GPU: AMD Radeon RX 7900 XTX
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221222.1749
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
No
```

**Comment by Ew4n1011** [comment]
When you install a new iso it does give you the option to preserve your home I think (from memory anyway), but there probably is a better way to update as well

**Comment by zweiler2** [comment]
If the installer detects a valid HoloISO home partition on the drive you selected to install to, it will ask you if you want to keep/reuse it.  
No data loss occurs then. Only the packages you installed via "pacman" from the terminal gets lost (but not its configuration or user data).  
Currently i only applied my changes to the ISO directly, so you'd have to always download the newest ISO to get my changes; planning on changing this.  
Will update the readme accordingly in about 2 weeks (currently on holiday).

**Comment by borger** [comment]
Thank you!
