### ISSUE TITLE
Iso 4.14 hotfix install/update problem

### ISSUE THREAD

**Issue by T0mu** [zweiler2/HoloISO_Nvidia#8]
Hi,
I recently updated an install and, somehow my "deck" user was not imported.
When I tried do delve a bit in the issue I discovered 4.1.4 hotfix creates a "liveuser" user instead of importing deck.

BTW thank you, I am finally testing SteamOS on my nvidia gfx all in one.

**Comment by zweiler2** [comment]
Hi @T0mu, I'm a bit late i know. Does this issue still exist in the newest ISO?
You're welcome; This was actually one of the reason why i started this fork.

**Comment by zweiler2** [comment]
Closing due to no response. Feel free to reopen if the issue persists in the newest ISO.
