### ISSUE TITLE
xorg.conf braks desktop mode or am i stupid :p

### ISSUE THREAD

**Issue by Askysoul** [zweiler2/HoloISO_Nvidia#9]
## Your Issue:

```xorg.con breaks the desktop mode hrmm ```

## Your device's full specs
```
CPU: i5 10300H
GPU: Nvidia GTX 1650Ti
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot 2022.12
```

## (Only for SteamOS Session loading issues) Have you tried launching `gamescope-session` from terminal? If yes, provide a log.
```
nothing here all works
```

## Your installation type:
```
deckperience
```

## Have you updated your installation recently?
```
noe
```

**Comment by Ew4n1011** [comment]
How exactly does it break it?

**Comment by Askysoul** [comment]
> How exactly does it break it?

Like i cant enter desktop mode using it 

To say properly (coolbits break it was trying to oc my 1650 now building kernel again to check if that helps ) it works with default xorg.conf
